## Make use of the following inbuilt api's
1. min
2. max
3. mean
4. argmin
5. argmax
6. linalg.solve
7. flatten
8. ravel
9. dot Product
10. \* for Matrix (Element wise multiplication)
11. arange followed by reshape
12. identity / eye
13. sum
14. diag
15. tril / triu



In [3]:
import numpy as np

In [4]:
b = np.arange(10)**3

### Part 1: Min value ###

In [5]:
min_value = np.min(b)

### Part 2: Max value ###

In [6]:
max_value = np.max(b)

### Part 3: Mean value ###

In [7]:
mean_value = np.mean(b)

### Part 4: Minimum argument value ###

In [8]:
argmin_value = np.argmin(b)

### Part 5: Maximum argument value ###

In [9]:
argmax_value = np.max(b)

### Part 6: linalg.solve()  ### 

Solve a linear matrix equation, or system of linear scalar equations.

In [11]:
f = np.array([[1, 1], [2, 3]])
y = np.array([2, 5])

In [13]:
solved = np.linalg.solve(f, y)

### Part 7: Flatten ###

In [25]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

flat_c = m.flatten(order = 'C')
flat_f = m.flatten(order = 'F')


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### Part 8: Ravel###

In [27]:
ravel_m = m.ravel()

### Part 9: Dot Product ###

In [29]:
g = np.array([[1, 2], [3, 4]])
h = np.array([[3, 4], [1, 2]])
dot_multi = np.dot(g,h)


array([[ 5,  8],
       [13, 20]])

### Part 10: Multiplication for matrix ###

In [32]:
mult_matrix = np.multiply(g, h)

### Part 11: Reshape ###

In [35]:
n_reshape = m.reshape(8, 2)

### Part 12: Eye

In [37]:
u = np.eye(2)

### Part 13: Sum ###

In [44]:
n_sum = m.sum(axis =  1)
n_sum

array([10, 26, 42, 58])

### Part 14: Diagonal elements ###

In [42]:
diag_element = m.diagonal()
diag_element

array([ 1,  6, 11, 16])

### Part 15: Triangular ###

In [47]:
upper_tri = np.tril([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
lower_tri = np.triu([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

Part 1: Min value

## Part - B ##

## For the all api's mentioned above implement your own version of it. Except linalg.solve. At minimum each implementation of yours should support 2d matrices. ##

In [84]:
a = [[1, 2, 3], [3, 4, 5], [4, 5, 6]]

np.array(a)

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

### Part 1: Min value ###

In [73]:
def mini(a):
    h = a[0][0]
    for i in range(len(a)):
        for j in range(len(a[i])):
            if (h > a[i][j]):
                h = a[i][j]
                
    return h
    
print (mini(a))

1


### Part 2: Max value ###

In [75]:
def maxi(a):
    h = a[0][0]
    for i in range(len(a)):
        for j in range(len(a[i])):
            if (h < a[i][j]):
                h = a[i][j]
                
    return h
    
print (maxi(a))

6


### Part 3: Mean value ###

In [77]:
def meani(a):
    summ = 0
    for i in range(len(a)):
        for j in range(len(a[i])):
            summ += a[i][j]
            
    lenght = len(a)*len(a[0])      
                
    return summ/lenght
    
print (meani(a))

3.6666666666666665


### Part 4: Minimum argument value ###

In [79]:
def argmini(a):
    h = a[0][0]
    count = 0
    mini_i = 0
    for i in range(len(a)):
        for j in range(len(a[i])):
            count += 1
            if (h > a[i][j]):
                h = a[i][j]
                mini_i = count
                
    return mini_i
    
print (argmini(a))

0


### Part 5: Maximum argument value ###

In [85]:
def argmaxi(a):
    h = a[0][0]
    count = 0
    max_i = 0
    for i in range(len(a)):
        for j in range(len(a[i])):
            count += 1
            if (h < a[i][j]):
                h = a[i][j]
                max_i = count
                
    return max_i
    
print (argmaxi(a))

9


### Part 6: Flatten ###

In [87]:
def aflat(a):
    h = []
    for i in range(len(a)):
        for j in range(len(a[i])):
            h.append(a[j][i])
            
                
    return h
    
print (aflat(a))

[1, 3, 4, 2, 4, 5, 3, 5, 6]


### Part 7: Ravel###

In [88]:
def arav(a):
    h = []
    for i in range(len(a)):
        for j in range(len(a[i])):
            h.append(a[i][j])
            
                
    return h
    
print (arav(a))

[1, 2, 3, 3, 4, 5, 4, 5, 6]


### Part 8: Dot Product ###

In [96]:
b = [[2, 3, 4], [3, 4, 5], [4, 5, 6]]

def dotpro(a,b):
    m1 = len(a)
    m2 = len(a[1])
    n1 = len(b)
    n2 = len(b[1])
    if (m2 == n1):
        dot_result = []
        for i in list(range(m1)):
            w = []
            for j in list(range(n2)):
                s = 0
                for k in list(range(m2)):
                    s=s + a[i][k] * b[k][j]
                w.append(s)
            dot_result.append(w)
    return(dot_result)
    
print (dotpro(a,b))
            

[[20, 26, 32], [38, 50, 62], [47, 62, 77]]


### Part 9: Multiplication for matrix ###

In [98]:
def mat_multi(a,b):
    m1 = len(a)
    m2 = len(a[1])
    n1 = len(b)
    n2 = len(b[1])
    h = []
    c = []
    if (m1 == n1 & m2 == n2 ):
        
        for i in range(len(a)):
            w = []
            for j in range(len(a[i])):
                h = a[i][j] * b[i][j]
                w.append(h)
            c.append(w)
                
    return c
    
print (mat_multi(a,b))

[[2, 6, 12], [9, 16, 25], [16, 25, 36]]


### Part 10: Reshape ###

In [102]:
def reshape_n(x ,n ,m):
    y = []
    k = 0
    for i in list(range(n)):
        w = []
        for j in list(range(m)):
                w.append(x[k])
                k = k + 1
        y.append(w)        
    return(y)
reshape_n([1 ,2 ,3 ,4 ,5 ,6],2 ,3)

[[1, 2, 3], [4, 5, 6]]

### Part 11: Eye

In [103]:
def iden_(n):
    c = []
    for i in list(range(n)):
        b = []
        for j in list(range(n)):
            if i == j:
                b.append(1)
            else:
                b.append(0)
        c.append(b)        
    return(c)
iden_(3)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [105]:
def eye_n(r ,c):
    m = []
    for i in list(range(r)):
        w = []
        for j in list(range(c)):
            if i == j:
                w.append(1)
            else:
                w.append(0)
        m.append(w)        
    return(m)
eye_n(3 ,3)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

### Part 12: Sum ###

In [106]:
def sum_(a):
    c = 0
    for i in list(range(len(a))):
        for j in list(range(len(a[0]))):
            c = c + a[i][j]
    return(c)
sum_(a)

33

### Part 13: Diagonal elements ###

In [107]:
def diag_(a):
    c = []
    for i in list(range(len(a))):
        for j in list(range(len(a[0]))):
            if i == j:
                c.append(a[i][j])
    return(c)
diag_(a)

[1, 4, 6]

### Part 14: Triangular ###

In [108]:
def tri_lower(a):
    c = []
    for i in list(range(len(a))):
        w = []
        for j in list(range(len(a[0]))):
            if i >= j:
                w.append(a[i][j])
            else:
                w.append(0)
        c.append(w)        
    return(c)
tri_lower(a)

[[1, 0, 0], [3, 4, 0], [4, 5, 6]]

In [109]:
def tri_upper(a):
    c = []
    for i in list(range(len(a))):
        w = []
        for j in list(range(len(a[0]))):
            if i <= j:
                w.append(a[i][j])
            else:
                w.append(0)
        c.append(w)        
    return(c)
tri_upper(a)

[[1, 2, 3], [0, 4, 5], [0, 0, 6]]